AllCops:
  Exclude:
    - cookbooks/**/*

Metrics/LineLength:
  Max: 120

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - site-cookbooks/**/*

Style/GlobalVars:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableInterpolation:
  Enabled: false
